server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: /home/ersan/development/workspaces/microservice-practicals/config-repo